name: Analyze Language Distribution

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *' # Runs daily at midnight

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run language distribution script
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          python your_script.py  # Replace 'your_script.py' with the actual script name

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          git add README.md language_distribution_bar_chart.png
          git commit -m "Update language distribution chart"
          git push
