name: Analyze Language Distribution

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib requests  

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Debug token visibility
        run: |
            if [ -z "$GITHUB_TOKEN" ]; then
              echo "GITHUB_TOKEN is not set"
            else
              echo "GITHUB_TOKEN is set"
            fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Run language distribution script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python fetch_github_languages.py  

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add README.md language_distribution_bar_chart.png
          git commit -m "Update language distribution chart"
          git push

